# Server port
server.port=8815

# Application name
spring.application.name=payment-service

# Eureka Client Config
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka
eureka.instance.prefer-ip-address=true

# Actuator Config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Feign Circuit Breaker Config
spring.cloud.openfeign.circuitbreaker.enabled=true
